### ISSUE TITLE
Name field convension

### ISSUE THREAD

**Issue by bdjunayed** [matesgroup/matesworkforce.com.au#9]
In the contact page, the name field must contain Aa to zZ small or caps.
Length no more than 40 char.

If the user input number / symbols then js msg, "Wrong input".

**Comment by illeas** [comment]
please have a look and close this issue

**Comment by bdjunayed** [comment]
need to support a spacebar.

**Comment by bdjunayed** [comment]
Please make resonable name lenght bellow 50
